baseURL = "https://diemoeve.github.io/"
languageCode = "en-us"
title = "moeve's blog"
theme = "archie"

# Turn on nice features for long writeups
enableRobotsTXT = true
[pagination]
  pagerSize = 15

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 4
    ordered    = false
  [markup.highlight]
    noClasses = false
    lineNos = true

# Menus
[menu]
  [[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1
  [[menu.main]]
    name = "Writeups"
    url  = "/writeups/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url  = "/tags/"
    weight = 3

# Optional: custom params used by Archie
[params]
  mode = "light"                # keep Bear-like minimalism
  description = "CTF writeups"
  useCDN = false
  subtitle = "I have participated in the HackTheBoo CTF 2025 and reached Top 5. Looking back, the categories Rev, Crypto and Pwn got the least solves overall, so I decided to make writeups for these categories."
  math = false
  customCSS = ["css/custom.css"]

# Permalinks: keep hierarchy visible
[permalinks]
  writeups = "/writeups/:sections/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
